"use client";
import { useState } from "react";
import { CheckCircle, Clock, Package, Search, Truck } from "lucide-react";

const steps=["pending","confirmed","processing","packed","ready_to_ship","shipped","out_for_delivery","delivered"];
const labels:Record<string,string>={pending:"Order placed",confirmed:"Confirmed",processing:"Processing",packed:"Packed",ready_to_ship:"Ready to ship",shipped:"Shipped",out_for_delivery:"Out for delivery",delivered:"Delivered",cancelled:"Cancelled",failed:"Failed"};
type TrackedOrder={public_order_id:string;order_status:string;payment_method:string;payment_status:string;total_amount:number;created_at:string;courier_name:string|null;courier_tracking_number:string|null;items:Array<{product_name:string;product_type:string;quantity:number;measurement_quantity:number|null;selling_unit:string|null;size:string|null;color:string|null;line_total:number}>;history:Array<{new_status:string;created_at:string}>};
const selection=(item:TrackedOrder["items"][number])=>[item.color,item.size,item.selling_unit?`${item.measurement_quantity??item.quantity} ${item.selling_unit}${Number(item.measurement_quantity??item.quantity)===1?"":"s"}`:null].filter(Boolean).join(" · ");

export default function TrackOrderPage(){
 const [reference,setReference]=useState(""); const [phone,setPhone]=useState(""); const [order,setOrder]=useState<TrackedOrder|null>(null); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
 async function submit(event:React.FormEvent){event.preventDefault();setLoading(true);setError("");setOrder(null);try{const response=await fetch("/api/orders/track",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({public_order_id:reference.trim().toUpperCase(),phone_number:phone})});if(!response.ok)throw new Error();const data=await response.json() as {order:TrackedOrder};setOrder(data.order);}catch{setError("Order not found. Check both the reference and phone number.");}finally{setLoading(false);}}
 const current=order?steps.indexOf(order.order_status):-1;
 return <main className="mx-auto max-w-4xl px-5 py-14"><div className="text-center"><Truck className="mx-auto text-brand-gold-dark" size={42}/><h1 className="mt-4 font-display text-4xl">Track Your Order</h1><p className="mt-2 text-muted">Enter your secure order reference and the mobile number used at checkout.</p></div>
 <form onSubmit={submit} className="my-9 grid gap-4 border border-border bg-surface p-6 sm:grid-cols-2"><div><label htmlFor="reference" className="mb-2 block text-sm font-medium">Order Reference</label><input id="reference" required pattern="QZF-[A-Fa-f0-9]{12}" value={reference} onChange={e=>setReference(e.target.value)} placeholder="QZF-8A4F2C7D9E10" className="w-full border border-border bg-bg px-4 py-3 font-mono uppercase"/></div><div><label htmlFor="phone" className="mb-2 block text-sm font-medium">Mobile Number</label><input id="phone" required inputMode="numeric" value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,"").slice(0,11))} placeholder="03XXXXXXXXX" className="w-full border border-border bg-bg px-4 py-3"/></div><button disabled={loading} className="flex items-center justify-center gap-2 bg-brand-green px-7 py-3 text-white disabled:opacity-50 sm:col-span-2"><Search size={17}/>{loading?"Checking…":"Track Order"}</button></form>
 {error&&<p role="alert" className="border border-error/30 bg-error/10 p-4 text-error">{error}</p>}
 {order&&<section className="space-y-6"><div className="border border-border bg-surface p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs uppercase text-muted">Order reference</p><p className="font-mono text-xl font-bold text-brand-green">{order.public_order_id}</p><p className="mt-1 text-sm text-muted">Placed {new Date(order.created_at).toLocaleDateString("en-PK")}</p></div><span className="bg-brand-green/10 px-3 py-2 text-sm font-semibold text-brand-green">{labels[order.order_status]||order.order_status}</span></div><div className="mt-8 grid grid-cols-4 gap-y-6 sm:grid-cols-8">{steps.map((step,index)=>{const Icon=index===0?Clock:index>=5?Truck:index===7?CheckCircle:Package;return <div key={step} className={`text-center ${index<=current?"text-brand-green":"text-muted/50"}`}><Icon className="mx-auto" size={22}/><span className="mt-2 block text-[10px] leading-tight">{labels[step]}</span></div>;})}</div></div>
 <div className="grid gap-6 md:grid-cols-2"><div className="border border-border bg-surface p-6"><h2 className="font-display text-xl">Order Summary</h2><div className="mt-4 space-y-3">{order.items.map((item,index)=><div key={`${item.product_name}-${index}`} className="flex justify-between gap-4 border-b border-border pb-3 text-sm"><span>{item.product_name}<small className="block text-muted">{selection(item)||`Qty ${item.quantity}`}</small></span><span>PKR {Number(item.line_total).toLocaleString()}</span></div>)}</div><p className="mt-4 flex justify-between font-bold"><span>Total</span><span>PKR {Number(order.total_amount).toLocaleString()}</span></p></div><div className="border border-border bg-surface p-6"><h2 className="font-display text-xl">Delivery & Payment</h2><dl className="mt-4 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-muted">Payment</dt><dd>Cash on Delivery</dd></div><div><dt className="text-muted">Payment status</dt><dd className="capitalize">{order.payment_status}</dd></div>{order.courier_name&&<div><dt className="text-muted">Courier</dt><dd>{order.courier_name}</dd></div>}{order.courier_tracking_number&&<div><dt className="text-muted">Courier tracking</dt><dd>{order.courier_tracking_number}</dd></div>}</dl></div></div>
 {order.history.length>0&&<div className="border border-border bg-surface p-6"><h2 className="font-display text-xl">Status History</h2><ol className="mt-4 space-y-3">{order.history.map((entry,index)=><li key={`${entry.created_at}-${index}`} className="flex justify-between gap-4 text-sm"><span>{labels[entry.new_status]||entry.new_status}</span><time className="text-muted">{new Date(entry.created_at).toLocaleString("en-PK")}</time></li>)}</ol></div>}</section>}
 </main>;
}
