"use client";

import Image from "next/image";
import Link from "next/link";
import { useRef, useState } from "react";
import { AlertCircle, CheckCircle, ChevronDown, CreditCard, LockKeyhole, Truck } from "lucide-react";
import { calculateDisplayedDelivery, pakistanProvinces } from "@/src/config/business";
import { useCartStore } from "@/src/store/useCartStore";
import { lineSelectionLabel } from "@/src/lib/product-commerce";

const STORAGE_KEY = "qurzaib-checkout-idempotency";
type FormState = { first_name:string; last_name:string; email:string; phone_number:string; delivery_address:string; address_line_2:string; area:string; city:string; province:string; postal_code:string; delivery_notes:string; payment_method:"cod" };
const initialForm: FormState = { first_name:"",last_name:"",email:"",phone_number:"",delivery_address:"",address_line_2:"",area:"",city:"",province:"",postal_code:"",delivery_notes:"",payment_method:"cod" };

function Field({ label, name, value, change, error, type="text", optional=false }: { label:string; name:keyof FormState; value:string; change:(name:keyof FormState,value:string)=>void; error?:string; type?:string; optional?:boolean }) {
  return <div><label htmlFor={name} className="mb-2 block text-sm font-medium">{label}{optional ? " (optional)" : " *"}</label><input id={name} type={type} value={value} onChange={(e)=>change(name,e.target.value)} aria-invalid={Boolean(error)} aria-describedby={error ? `${name}-error` : undefined} className={`w-full border bg-bg px-4 py-3 outline-none focus:border-accent ${error ? "border-error" : "border-border"}`} />{error && <p id={`${name}-error`} className="mt-1 text-xs text-error">{error}</p>}</div>;
}

export default function CheckoutPage() {
  const { cart, clearCart } = useCartStore();
  const [form,setForm] = useState<FormState>(initialForm);
  const [errors,setErrors] = useState<Record<string,string>>({});
  const [submitting,setSubmitting] = useState(false);
  const [error,setError] = useState<string|null>(null);
  const [confirmation,setConfirmation] = useState<{reference:string;total:number;customerName:string;email:string;emailAccepted:boolean}|null>(null);
  const [paymentChoice,setPaymentChoice] = useState<"cod"|"card_demo">("cod");
  const [billingSame,setBillingSame] = useState(true);
  const [offers,setOffers] = useState(false);
  const keyRef = useRef("");
  const submitInFlightRef = useRef(false);
  const subtotal = cart.reduce((sum,item)=>sum+item.price*item.quantity,0);
  const delivery = calculateDisplayedDelivery(subtotal);
  const change = (name:keyof FormState,value:string) => { setForm(current=>({...current,[name]:value})); setErrors(current=>({...current,[name]:""})); };
  function validate() { const next:Record<string,string>={}; if(form.first_name.trim().length<2)next.first_name="Enter your first name."; if(form.last_name.trim().length<2)next.last_name="Enter your last name."; if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email.trim()))next.email="Enter a valid email."; if(!/^03\d{9}$/.test(form.phone_number.replace(/\D/g,"")))next.phone_number="Use 03XXXXXXXXX."; if(form.delivery_address.trim().length<10)next.delivery_address="Enter a complete address."; if(form.area.trim().length<2)next.area="Enter your area."; if(form.city.trim().length<2)next.city="Enter your city."; if(!form.province)next.province="Select a province."; setErrors(next); return !Object.keys(next).length; }
  async function submit(event:React.FormEvent){ event.preventDefault(); if(submitInFlightRef.current)return; setError(null); if(!validate()||!cart.length)return; submitInFlightRef.current=true; setSubmitting(true); try { const items=cart.map(({id,variantId,quantity,sellingUnit})=>({product_id:id,variant_id:variantId??null,quantity,...(sellingUnit?{selling_unit:sellingUnit}:{})})); const fingerprint=JSON.stringify(items); if(!keyRef.current){ try { const saved=JSON.parse(sessionStorage.getItem(STORAGE_KEY)||"null") as {fingerprint?:string;key?:string}|null; keyRef.current=saved?.fingerprint===fingerprint&&saved.key?saved.key:crypto.randomUUID(); } catch { keyRef.current=crypto.randomUUID(); } sessionStorage.setItem(STORAGE_KEY,JSON.stringify({fingerprint,key:keyRef.current})); } const { first_name, last_name, ...checkoutFields } = form; const customerName=`${first_name.trim()} ${last_name.trim()}`; const response=await fetch("/api/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...checkoutFields,customer_name:customerName,phone_number:form.phone_number.replace(/\D/g,""),idempotency_key:keyRef.current,items})}); const result=await response.json() as {message?:string;orderReference?:string;total?:number;customerEmailAccepted?:boolean}; if(!response.ok||!result.orderReference)throw new Error(result.message||"Unable to place order"); setConfirmation({reference:result.orderReference,total:Number(result.total),customerName,email:form.email.trim(),emailAccepted:result.customerEmailAccepted===true}); clearCart(); sessionStorage.removeItem(STORAGE_KEY); keyRef.current=""; } catch(caught){setError(caught instanceof Error?caught.message:"Unable to place order");} finally{submitInFlightRef.current=false;setSubmitting(false);} }

  if(confirmation)return <main className="mx-auto max-w-xl px-5 py-20 text-center"><CheckCircle className="mx-auto mb-5 text-success" size={64}/><p className="text-xs uppercase tracking-[.22em] text-brand-gold-dark">Order confirmed</p><h1 className="mt-3 font-display text-4xl">Thank you, {confirmation.customerName}!</h1><div className="my-8 border border-border bg-surface p-6 text-left"><p className="text-xs uppercase text-muted">Order ID</p><p className="mt-1 font-mono text-2xl font-bold text-brand-charcoal">{confirmation.reference}</p><div className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><p className="text-muted">Payment</p><p>Cash on Delivery</p></div><div><p className="text-muted">Total</p><p>Rs. {confirmation.total.toLocaleString("en-PK")}</p></div><div><p className="text-muted">Status</p><p>Pending confirmation</p></div></div></div><p className="mb-7 text-sm text-muted">{confirmation.emailAccepted?`A confirmation email has been sent to ${confirmation.email}.`:"Your order has been confirmed. You can track it using your order ID."}</p><div className="flex flex-col justify-center gap-3 sm:flex-row"><Link href={`/track-order?reference=${confirmation.reference}`} className="bg-brand-charcoal px-6 py-3 text-white">Track Order</Link><Link href="/" className="border border-brand-charcoal px-6 py-3 text-brand-charcoal">Continue Shopping</Link></div></main>;
  if(!cart.length)return <main className="mx-auto max-w-xl px-5 py-24 text-center"><h1 className="font-display text-4xl">Your cart is empty</h1><p className="mt-3 text-muted">Add an item before starting checkout.</p><Link href="/collections" className="mt-7 inline-block bg-brand-green px-6 py-3 text-white">Browse Collections</Link></main>;

  return <main className="mx-auto max-w-7xl px-5 py-10 sm:px-8"><p className="text-xs uppercase tracking-[.2em] text-brand-gold-dark">Secure checkout</p><h1 className="mb-7 font-display text-4xl">Complete Your Order</h1>{error&&<div role="alert" className="mb-6 flex gap-2 border border-error/30 bg-error/10 p-4 text-error"><AlertCircle size={18}/>{error}</div>}<details className="mb-7 border border-border bg-surface lg:hidden"><summary className="flex cursor-pointer list-none items-center justify-between p-4 font-semibold">Order summary · PKR {(subtotal+delivery).toLocaleString()} <ChevronDown size={18}/></summary><div className="space-y-3 border-t border-border p-4">{cart.map(item=><div key={item.lineKey} className="flex justify-between gap-3 text-sm"><span className="min-w-0 truncate">{item.title} · {lineSelectionLabel(item)} × {item.quantity}</span><span>PKR {(item.price*item.quantity).toLocaleString()}</span></div>)}<p className="flex justify-between border-t border-border pt-3 text-sm"><span>Delivery</span><span>{delivery?`PKR ${delivery}`:"Free"}</span></p></div></details><div className="grid gap-10 lg:grid-cols-[1.25fr_.75fr]"><form onSubmit={(event)=>{if(paymentChoice==="cod")void submit(event);else{event.preventDefault();setError("Card payment is a visual demo only. Choose Cash on Delivery to place this order securely.");}}} noValidate className="space-y-8">
    <fieldset className="grid gap-5 border border-border bg-surface p-5 sm:grid-cols-2 sm:p-7"><legend className="px-2 font-display text-xl">Contact</legend><Field label="Email Address" name="email" type="email" value={form.email} change={change} error={errors.email}/><Field label="Mobile Number" name="phone_number" type="tel" value={form.phone_number} change={change} error={errors.phone_number}/><label className="flex items-start gap-2 text-sm sm:col-span-2"><input type="checkbox" checked={offers} onChange={(event)=>setOffers(event.target.checked)} className="mt-0.5 accent-brand-green"/> Email me QurZaib Fabrics news and offers (optional).</label></fieldset>
    <fieldset className="grid gap-5 border border-border bg-surface p-5 sm:grid-cols-2 sm:p-7"><legend className="px-2 font-display text-xl">Delivery Address</legend><div className="sm:col-span-2"><label htmlFor="country" className="mb-2 block text-sm font-medium">Country / Region</label><select id="country" value="Pakistan" disabled className="w-full border border-border bg-bg px-4 py-3 text-brand-charcoal disabled:opacity-100"><option>Pakistan</option></select></div><Field label="First Name" name="first_name" value={form.first_name} change={change} error={errors.first_name}/><Field label="Last Name" name="last_name" value={form.last_name} change={change} error={errors.last_name}/><div className="sm:col-span-2"><Field label="Full Address" name="delivery_address" value={form.delivery_address} change={change} error={errors.delivery_address}/></div><div className="sm:col-span-2"><Field label="Apartment / House / Floor" name="address_line_2" value={form.address_line_2} change={change} optional/></div><Field label="Area" name="area" value={form.area} change={change} error={errors.area}/><Field label="City" name="city" value={form.city} change={change} error={errors.city}/><div><label htmlFor="province" className="mb-2 block text-sm font-medium">Province *</label><select id="province" value={form.province} onChange={(e)=>change("province",e.target.value)} aria-invalid={Boolean(errors.province)} aria-describedby={errors.province ? "province-error" : undefined} className="w-full border border-border bg-bg px-4 py-3"><option value="">Select province</option>{pakistanProvinces.map(item=><option key={item}>{item}</option>)}</select>{errors.province&&<p id="province-error" className="mt-1 text-xs text-error">{errors.province}</p>}</div><Field label="Postal Code" name="postal_code" value={form.postal_code} change={change} optional/><div className="sm:col-span-2"><label htmlFor="delivery_notes" className="mb-2 block text-sm font-medium">Delivery Notes (optional)</label><textarea id="delivery_notes" value={form.delivery_notes} maxLength={500} rows={3} onChange={(e)=>change("delivery_notes",e.target.value)} className="w-full border border-border bg-bg px-4 py-3"/></div></fieldset>
    <fieldset className="border border-border bg-surface p-5 sm:p-7"><legend className="px-2 font-display text-xl">Shipping Method</legend><div className="flex items-center justify-between gap-4 border border-brand-green bg-brand-green/5 p-4 text-sm"><span className="flex items-center gap-3"><Truck size={20}/><span><strong className="block">Standard delivery</strong><span className="text-muted">Across Pakistan</span></span></span><strong>{delivery?`PKR ${delivery}`:"FREE"}</strong></div></fieldset>
    <fieldset className="border border-border bg-surface p-5 sm:p-7"><legend className="px-2 font-display text-xl">Payment</legend><label className={`flex cursor-pointer gap-3 border p-4 ${paymentChoice==="cod"?"border-brand-green bg-brand-green/5":"border-border"}`}><input type="radio" name="payment_choice" checked={paymentChoice==="cod"} onChange={()=>setPaymentChoice("cod")} className="accent-brand-green"/><span><strong>Cash on Delivery</strong><span className="block text-sm text-muted">Pay on arrival. Your order starts as unpaid.</span></span></label><label className={`mt-3 flex cursor-pointer gap-3 border p-4 ${paymentChoice==="card_demo"?"border-brand-green bg-brand-green/5":"border-border"}`}><input type="radio" name="payment_choice" checked={paymentChoice==="card_demo"} onChange={()=>setPaymentChoice("card_demo")} className="accent-brand-green"/><CreditCard size={20}/><span><strong>Debit / Credit Card</strong><span className="block text-sm text-muted">Demo preview only — online payment is not connected.</span></span></label>{paymentChoice==="card_demo"&&<div className="mt-3 grid gap-3 border border-border bg-bg p-4 sm:grid-cols-2"><label className="text-xs sm:col-span-2">Card number<input inputMode="numeric" autoComplete="cc-number" placeholder="0000 0000 0000 0000" className="mt-1 block w-full border border-border bg-white px-3 py-3"/></label><label className="text-xs">Expiry<input autoComplete="cc-exp" placeholder="MM / YY" className="mt-1 block w-full border border-border bg-white px-3 py-3"/></label><label className="text-xs">Security code<input inputMode="numeric" autoComplete="cc-csc" placeholder="CVC" className="mt-1 block w-full border border-border bg-white px-3 py-3"/></label><label className="flex items-center gap-2 text-sm sm:col-span-2"><input type="checkbox" checked={billingSame} onChange={(event)=>setBillingSame(event.target.checked)} className="accent-brand-green"/> Billing address is the same as shipping</label>{!billingSame&&<p className="text-xs text-error sm:col-span-2">Separate billing address will be enabled with the real payment provider.</p>}<p className="text-xs text-muted sm:col-span-2">No card data is submitted or stored.</p></div>}</fieldset><button disabled={submitting||paymentChoice!=="cod"} className="flex w-full items-center justify-center gap-2 bg-brand-green py-4 font-semibold uppercase text-white disabled:cursor-not-allowed disabled:opacity-50"><LockKeyhole size={17}/>{paymentChoice==="card_demo"?"Pay Now — Demo Only":submitting?"Placing Order…":"Place COD Order"}</button></form>
    <aside className="hidden h-fit border border-border bg-surface p-5 lg:sticky lg:top-32 lg:block"><h2 className="font-display text-2xl">Order Summary</h2><div className="mt-5 space-y-4">{cart.map(item=><div key={item.lineKey} className="flex gap-3"><div className="relative h-20 w-16 shrink-0 bg-bg"><Image src={item.image} alt="" fill sizes="64px" className="object-cover"/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{item.title}</p><p className="text-xs text-muted">{lineSelectionLabel(item)} · Qty {item.quantity}</p></div><p className="text-sm">PKR {(item.price*item.quantity).toLocaleString()}</p></div>)}</div><div className="mt-6 space-y-2 border-t border-border pt-5 text-sm"><p className="flex justify-between"><span>Subtotal</span><span>PKR {subtotal.toLocaleString()}</span></p><p className="flex justify-between"><span>Delivery</span><span>{delivery?`PKR ${delivery}`:"Free"}</span></p><p className="flex justify-between border-t border-border pt-3 text-lg font-bold"><span>Total</span><span>PKR {(subtotal+delivery).toLocaleString()}</span></p><p className="pt-2 text-xs text-muted">Display estimate only. The server recalculates price, stock and delivery.</p></div></aside></div></main>;
}
