"use client";
import Link from"next/link";import{useCallback,useEffect,useState}from"react";import{LogOut,Package,Plus,RefreshCw,Search,ShoppingBag}from"lucide-react";import{createClient}from"@/src/lib/supabase/Client";
type AdminOrder={id:string;public_order_id:string;customer_name:string;phone_number:string;created_at:string;total_amount:number;payment_method:string;payment_status:string;order_status:string;items:unknown[]};
const statuses=["","pending","confirmed","processing","packed","ready_to_ship","shipped","out_for_delivery","delivered","cancelled"];
export default function AdminPortalPage(){const[orders,setOrders]=useState<AdminOrder[]>([]);const[count,setCount]=useState(0);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[search,setSearch]=useState("");const[status,setStatus]=useState("");const[page,setPage]=useState(1);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const params=new URLSearchParams({page:String(page),search,status});const response=await fetch(`/api/admin/orders?${params}`);if(response.status===401){window.location.assign("/admin-login");return;}if(!response.ok)throw new Error();const data=await response.json()as{orders:AdminOrder[];count:number};setOrders(data.orders);setCount(data.count);}catch{setError("Unable to load orders.");}finally{setLoading(false);}},[page,search,status]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),200);return()=>window.clearTimeout(timer);},[load]);
 async function logout(){await createClient().auth.signOut();window.location.assign("/admin-login");}
 const pending=orders.filter(o=>o.order_status==="pending").length;const revenue=orders.filter(o=>o.order_status==="delivered").reduce((sum,o)=>sum+Number(o.total_amount),0);
 return <main className="min-h-screen bg-bg"><header className="border-b border-border bg-brand-green-dark px-5 py-4 text-white"><div className="mx-auto flex max-w-7xl items-center justify-between"><div><p className="font-display text-xl">QurZaib Operations</p><p className="text-xs text-white/60">Authenticated administration</p></div><button onClick={logout} className="flex items-center gap-2 text-sm"><LogOut size={16}/>Logout</button></div></header><div className="mx-auto max-w-7xl px-5 py-8">
 <div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="font-display text-4xl">Orders</h1><p className="text-sm text-muted">Controlled fulfillment and payment operations</p></div><div className="flex gap-2"><Link href="/admin-portal/products/new" className="flex items-center gap-2 border border-brand-green px-4 py-2 text-sm text-brand-green"><Plus size={16}/>Add Product</Link><button onClick={()=>void load()} className="p-2 text-brand-green" aria-label="Refresh orders"><RefreshCw size={19}/></button></div></div>
 <section className="my-7 grid gap-4 sm:grid-cols-3"><article className="border border-border bg-white p-5"><ShoppingBag className="text-brand-gold-dark"/><p className="mt-3 text-2xl font-bold">{count}</p><p className="text-sm text-muted">Matching orders</p></article><article className="border border-border bg-white p-5"><Package className="text-brand-gold-dark"/><p className="mt-3 text-2xl font-bold">{pending}</p><p className="text-sm text-muted">Pending on this page</p></article><article className="border border-border bg-white p-5"><p className="text-xs uppercase text-brand-gold-dark">Delivered revenue</p><p className="mt-3 text-2xl font-bold">PKR {revenue.toLocaleString()}</p><p className="text-sm text-muted">Current page only</p></article></section>
 <div className="mb-4 grid gap-3 border border-border bg-white p-4 sm:grid-cols-[1fr_220px]"><label className="relative"><span className="sr-only">Search orders</span><Search className="absolute left-3 top-3.5 text-muted" size={17}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Reference or phone" className="w-full border border-border py-3 pl-10 pr-3"/></label><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} className="border border-border px-3"><option value="">All statuses</option>{statuses.filter(Boolean).map(item=><option key={item} value={item}>{item.replaceAll("_"," ")}</option>)}</select></div>
 {error&&<p role="alert" className="mb-4 bg-error/10 p-4 text-error">{error}</p>}<div className="overflow-x-auto border border-border bg-white"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-brand-cream text-xs uppercase"><tr>{["Reference","Customer","Date","Amount","Payment","Status","Items",""].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-border">{orders.map(order=><tr key={order.id}><td className="px-4 py-4 font-mono font-semibold text-brand-green">{order.public_order_id}</td><td className="px-4 py-4"><span className="block">{order.customer_name}</span><span className="text-xs text-muted">{order.phone_number}</span></td><td className="px-4 py-4">{new Date(order.created_at).toLocaleDateString("en-PK")}</td><td className="px-4 py-4">PKR {Number(order.total_amount).toLocaleString()}</td><td className="px-4 py-4 capitalize">{order.payment_method}<span className="block text-xs text-muted">{order.payment_status}</span></td><td className="px-4 py-4 capitalize">{order.order_status.replaceAll("_"," ")}</td><td className="px-4 py-4">{Array.isArray(order.items)?order.items.length:0}</td><td className="px-4 py-4"><Link href={`/admin-portal/orders/${order.id}`} className="font-semibold text-brand-green">Manage</Link></td></tr>)}</tbody></table>{loading&&<p className="p-8 text-center text-muted">Loading orders…</p>}{!loading&&!orders.length&&<p className="p-8 text-center text-muted">No matching orders.</p>}</div><div className="mt-5 flex justify-between"><button disabled={page===1} onClick={()=>setPage(p=>p-1)} className="border px-4 py-2 disabled:opacity-40">Previous</button><span className="text-sm text-muted">Page {page}</span><button disabled={page*20>=count} onClick={()=>setPage(p=>p+1)} className="border px-4 py-2 disabled:opacity-40">Next</button></div>
 </div></main>}
