"use client";
import Image from "next/image";
import { useState } from "react";
import { createClient } from "@/src/lib/supabase/Client";
type Row={id:string;name:string;slug:string;description?:string|null;image_url?:string|null;parent_id?:string|null;hex_code?:string|null;sort_order:number;is_active:boolean};
const CATEGORY_IMAGE_TYPES=new Set(["image/jpeg","image/png","image/webp"]);
export function TaxonomyManager({table,initialRows,allowParent=false,allowHex=false}:{table:"categories"|"collections"|"colors";initialRows:Row[];allowParent?:boolean;allowHex?:boolean}){
 const [rows,setRows]=useState(initialRows),[editing,setEditing]=useState<Row|null>(null),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false);const supabase=createClient();
 const blank:Row={id:"",name:"",slug:"",description:"",image_url:"",parent_id:null,hex_code:null,sort_order:rows.length*10,is_active:true},form=editing??blank;
 function change<K extends keyof Row>(key:K,value:Row[K]){setEditing({...form,[key]:value})}
 async function uploadCategoryImage(event:React.ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value="";if(!file)return;if(!CATEGORY_IMAGE_TYPES.has(file.type)||file.size>5*1024*1024){alert("Use a JPG, PNG, or WebP image up to 5 MB.");return}setUploading(true);try{const extension=file.type==="image/jpeg"?"jpg":file.type.split("/")[1],path=`categories/${crypto.randomUUID()}.${extension}`;const {error}=await supabase.storage.from("products").upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;change("image_url",supabase.storage.from("products").getPublicUrl(path).data.publicUrl)}catch(error){alert(error instanceof Error?error.message:"Unable to upload image")}finally{setUploading(false)}}
 async function save(event:React.FormEvent){event.preventDefault();setBusy(true);try{const payload={name:form.name.trim(),slug:form.slug.trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,""),sort_order:Number(form.sort_order),is_active:form.is_active,...(table!=="colors"?{description:form.description||null,image_url:form.image_url||null}:{}),...(allowParent?{parent_id:form.parent_id||null}:{}),...(allowHex?{hex_code:form.hex_code||null}:{})};const query=form.id?supabase.from(table).update(payload).eq("id",form.id):supabase.from(table).insert(payload).select().single();const {data,error}=await query;if(error)throw error;if(form.id)setRows(current=>current.map(row=>row.id===form.id?{...row,...payload}:row));else if(data)setRows(current=>[...current,data as Row]);setEditing(null)}catch(error){alert(error instanceof Error?error.message:"Unable to save")}finally{setBusy(false)}}
 async function archive(row:Row){const {error}=await supabase.from(table).update({is_active:!row.is_active}).eq("id",row.id);if(error){alert("Unable to update status");return}setRows(current=>current.map(item=>item.id===row.id?{...item,is_active:!item.is_active}:item))}
 return <div className="grid gap-6 xl:grid-cols-[1fr_380px]">
  <div className="overflow-x-auto rounded-lg border border-[#E5E7EB] bg-white"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-[#F9FAFB] text-xs uppercase text-[#6B7280]"><tr><th className="px-5 py-3">Name</th>{table==="categories"&&<th className="px-5 py-3">Image</th>}{allowParent&&<th className="px-5 py-3">Parent</th>}<th className="px-5 py-3">Order</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Actions</th></tr></thead><tbody className="divide-y">{[...rows].sort((a,b)=>a.sort_order-b.sort_order).map(row=><tr key={row.id}><td className="px-5 py-4"><strong>{row.name}</strong><p className="text-xs text-[#6B7280]">/{row.slug}</p></td>{table==="categories"&&<td className="px-5 py-4"><div className="relative h-12 w-12 overflow-hidden rounded-full border border-[#E5E7EB] bg-[#F7F3ED]">{row.image_url?<Image src={row.image_url} alt="" fill sizes="48px" className="object-cover"/>:<span className="grid h-full place-items-center text-sm font-semibold text-[#9D7B3F]">{row.name.trim().charAt(0).toUpperCase()}</span>}</div></td>}{allowParent&&<td className="px-5 py-4">{rows.find(item=>item.id===row.parent_id)?.name??"—"}</td>}<td className="px-5 py-4">{row.sort_order}</td><td className="px-5 py-4">{row.is_active?"Active":"Archived"}</td><td className="px-5 py-4"><button onClick={()=>setEditing(row)} className="mr-4 font-medium text-[#7A5B22]">Edit</button><button onClick={()=>void archive(row)} className="text-[#6B7280]">{row.is_active?"Archive":"Activate"}</button></td></tr>)}</tbody></table></div>
  <form onSubmit={save} className="h-fit space-y-4 rounded-lg border border-[#E5E7EB] bg-white p-5"><h2 className="text-lg font-semibold">{form.id?"Edit":"Add"} {table.slice(0,-1)}</h2><label className="block text-sm">Name<input required value={form.name} onChange={e=>change("name",e.target.value)} className="mt-1 h-11 w-full rounded border px-3"/></label><label className="block text-sm">Slug<input required value={form.slug} onChange={e=>change("slug",e.target.value)} className="mt-1 h-11 w-full rounded border px-3"/></label>{table!=="colors"&&<><label className="block text-sm">Description<textarea value={form.description??""} onChange={e=>change("description",e.target.value)} className="mt-1 w-full rounded border p-3"/></label>{table==="categories"?<div><label htmlFor="category-image" className="block text-sm">Category image</label><input id="category-image" type="file" accept="image/jpeg,image/png,image/webp" onChange={uploadCategoryImage} disabled={uploading} className="mt-2 block w-full text-sm"/><p className="mt-1 text-xs text-[#6B7280]">JPG, PNG, or WebP up to 5 MB.</p>{form.image_url&&<div className="mt-3 flex items-center gap-3"><div className="relative h-24 w-24 overflow-hidden rounded-full border bg-[#F7F3ED]"><Image src={form.image_url} alt={`${form.name||"Category"} preview`} fill sizes="96px" className="object-cover"/></div><button type="button" onClick={()=>change("image_url",null)} className="text-sm text-[#6B7280] underline">Remove image</button></div>}</div>:<label className="block text-sm">Image URL<input type="url" value={form.image_url??""} onChange={e=>change("image_url",e.target.value)} className="mt-1 h-11 w-full rounded border px-3"/></label>}</>}{allowHex&&<label className="block text-sm">Hex color<input pattern="#[0-9A-Fa-f]{6}" value={form.hex_code??""} onChange={e=>change("hex_code",e.target.value)} placeholder="#000000" className="mt-1 h-11 w-full rounded border px-3"/></label>}{allowParent&&<label className="block text-sm">Parent<select value={form.parent_id??""} onChange={e=>change("parent_id",e.target.value||null)} className="mt-1 h-11 w-full rounded border px-3"><option value="">None</option>{rows.filter(row=>row.id!==form.id&&!row.parent_id).map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label>}<label className="block text-sm">Sort order<input type="number" value={form.sort_order} onChange={e=>change("sort_order",Number(e.target.value))} className="mt-1 h-11 w-full rounded border px-3"/></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.is_active} onChange={e=>change("is_active",e.target.checked)}/>Active</label><div className="flex gap-2"><button disabled={busy||uploading} className="rounded bg-[#1A1A1A] px-4 py-2 text-white disabled:opacity-50">{uploading?"Uploading…":busy?"Saving…":"Save"}</button>{editing&&<button type="button" onClick={()=>setEditing(null)} className="rounded border px-4 py-2">Cancel</button>}</div></form>
 </div>
}
