"use client";
import { useCallback, useEffect, useState } from "react";
import { RefreshCw, Search } from "lucide-react";
import { OrderActions } from "@/src/components/admin/OrderActions";

type AdminOrder = { id:string; public_order_id:string; customer_name:string; email:string|null; phone_number:string; created_at:string; total_amount:number; payment_method:string; payment_status:string; order_status:string; items:unknown[] };
const statuses = ["", "pending", "confirmed", "processing", "packed", "ready_to_ship", "shipped", "out_for_delivery", "delivered", "cancelled"];
const paymentStatuses = ["", "pending", "unpaid", "paid", "failed", "refunded", "partially_refunded"];

export default function OrdersPage() {
  const [orders,setOrders]=useState<AdminOrder[]>([]); const [count,setCount]=useState(0); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [search,setSearch]=useState(""); const [status,setStatus]=useState(""); const [paymentStatus,setPaymentStatus]=useState(""); const [page,setPage]=useState(1);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const params=new URLSearchParams({page:String(page),search,status,paymentStatus});const response=await fetch(`/api/admin/orders?${params}`);if(response.status===401||response.status===403){window.location.assign("/admin-login");return;}if(!response.ok)throw new Error();const data=await response.json()as{orders:AdminOrder[];count:number};setOrders(data.orders);setCount(data.count);}catch{setError("Unable to load orders.");}finally{setLoading(false);}},[page,search,status,paymentStatus]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),250);return()=>window.clearTimeout(timer);},[load]);
  function removed(id:string){setOrders(current=>current.filter(order=>order.id!==id));setCount(current=>Math.max(0,current-1));setMessage("Order deleted successfully.")}
  return <main className="mx-auto max-w-[1500px]"><div className="mb-6 flex items-end justify-between gap-4"><div><h2 className="text-2xl font-semibold">Orders</h2><p className="mt-1 text-sm text-[#6B7280]">{count} matching orders</p></div><button type="button" onClick={()=>void load()} disabled={loading} aria-label="Refresh orders" className="grid h-10 w-10 place-items-center rounded-md border border-[#E5E7EB] bg-white disabled:opacity-50"><RefreshCw size={17}/></button></div>
    <div className="mb-5 grid gap-3 rounded-lg border border-[#E5E7EB] bg-white p-4 md:grid-cols-[1fr_200px_200px]"><label className="relative"><span className="sr-only">Search orders</span><Search className="absolute left-3 top-3 text-[#6B7280]" size={17}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Order, customer, email or phone" className="h-11 w-full rounded-md border border-[#E5E7EB] pl-10 pr-3"/></label><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} className="h-11 rounded-md border border-[#E5E7EB] px-3"><option value="">All order statuses</option>{statuses.filter(Boolean).map(item=><option key={item} value={item}>{item.replaceAll("_"," ")}</option>)}</select><select value={paymentStatus} onChange={e=>{setPaymentStatus(e.target.value);setPage(1)}} className="h-11 rounded-md border border-[#E5E7EB] px-3"><option value="">All payment statuses</option>{paymentStatuses.filter(Boolean).map(item=><option key={item} value={item}>{item.replaceAll("_"," ")}</option>)}</select></div>
    {message&&<p role="status" className="mb-4 rounded-md border border-emerald-200 bg-emerald-50 p-4 text-emerald-800">{message}</p>}{error&&<p role="alert" className="mb-4 rounded-md bg-[#B44343]/10 p-4 text-[#B44343]">{error}</p>}<div className="overflow-x-auto rounded-lg border border-[#E5E7EB] bg-white shadow-sm"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-[#F9FAFB] text-xs uppercase text-[#6B7280]"><tr>{["Reference","Customer","Phone","Date","Items","Total","Payment","Status","Action"].map(h=><th key={h} className="px-5 py-3 font-medium">{h}</th>)}</tr></thead><tbody className="divide-y divide-[#E5E7EB]">{orders.map(order=><tr key={order.id}><td className="px-5 py-4 font-mono text-xs font-semibold">{order.public_order_id}</td><td className="px-5 py-4"><span className="block font-medium">{order.customer_name}</span><span className="text-xs text-[#6B7280]">{order.email}</span></td><td className="px-5 py-4">{order.phone_number}</td><td className="px-5 py-4 text-[#6B7280]">{new Date(order.created_at).toLocaleDateString("en-PK")}</td><td className="px-5 py-4">{Array.isArray(order.items)?order.items.length:0}</td><td className="px-5 py-4 font-medium">Rs. {Number(order.total_amount).toLocaleString("en-PK")}</td><td className="px-5 py-4 capitalize">{order.payment_method}<span className="block text-xs text-[#6B7280]">{order.payment_status}</span></td><td className="px-5 py-4 capitalize">{order.order_status.replaceAll("_"," ")}</td><td className="px-5 py-4"><OrderActions id={order.id} reference={order.public_order_id} status={order.order_status} onDeleted={removed}/></td></tr>)}</tbody></table>{loading&&<p className="p-8 text-center text-sm text-[#6B7280]">Loading orders…</p>}{!loading&&!orders.length&&<p className="p-8 text-center text-sm text-[#6B7280]">No matching orders.</p>}</div><div className="mt-5 flex justify-between"><button disabled={page===1} onClick={()=>setPage(p=>p-1)} className="rounded-md border bg-white px-4 py-2 text-sm disabled:opacity-40">Previous</button><span className="text-sm text-[#6B7280]">Page {page}</span><button disabled={page*20>=count} onClick={()=>setPage(p=>p+1)} className="rounded-md border bg-white px-4 py-2 text-sm disabled:opacity-40">Next</button></div>
  </main>;
}
