export const commonReview="This template describes the intended customer process without creating an unconfirmed guarantee. Eligibility, timing, exceptions, contact details, and governing jurisdiction require owner and Pakistani legal review before publication as final terms.";
export const policyContent={
 cookies:{title:"Cookies Policy",intro:"How QurZaib Fabrics uses browser storage and optional technologies.",sections:[{title:"Necessary storage",body:"Cart contents, checkout idempotency, and cookie choices use local or session storage so requested features work."},{title:"Optional categories",body:"Analytics and marketing remain disabled unless you choose them. No analytics or marketing provider is currently configured."},{title:"Managing choices",body:"Use Cookie Preferences in the footer at any time."}]},
 refund:{title:"Refund Policy",intro:"A plain-language framework for reviewing approved refunds.",sections:[{title:"Eligibility",body:commonReview},{title:"Method and timing",body:"Approved refund method and processing time: OWNER_REVIEW_REQUIRED. Cash-on-delivery orders are not marked paid at creation."}]},
 cancellation:{title:"Cancellation Policy",intro:"How customers may request an order cancellation.",sections:[{title:"Requesting cancellation",body:"Contact support with the secure order reference and checkout phone number. A request is not a confirmed cancellation until reviewed."},{title:"Fulfillment stage",body:commonReview}]},
 returns:{title:"Return / Exchange Policy",intro:"A review framework for return and exchange requests.",sections:[{title:"Eligibility and window",body:"Return window, condition requirements, exclusions, and shipping responsibility: OWNER_REVIEW_REQUIRED."},{title:"Start a request",body:"Contact support without publishing sensitive order details. Keep packaging and proof of purchase until reviewed."}]},
 disclaimer:{title:"Disclaimer",intro:"Important limitations about catalog presentation and information.",sections:[{title:"Product presentation",body:"Screen settings and photography can affect perceived color. Product descriptions should be checked against the delivered item."},{title:"Business terms",body:commonReview}]},
 accessibility:{title:"Accessibility Statement",intro:"QurZaib Fabrics aims to provide an inclusive shopping experience.",sections:[{title:"Our approach",body:"We work toward keyboard access, visible focus, meaningful labels, readable contrast, reduced motion, and responsive layouts."},{title:"Feedback",body:"If a barrier prevents access, contact details are OWNER_REVIEW_REQUIRED. Include the affected page without sending payment credentials."}]},
 security:{title:"Security Policy",intro:"How QurZaib Fabrics protects commerce operations and customer data.",sections:[{title:"Controls",body:"Server-authoritative pricing, atomic inventory handling, role-based administration, row-level security, and two-factor order lookup protect core workflows."},{title:"Boundaries",body:"Never send passwords, card numbers, CVV, secret keys, or authentication tokens through support forms."}]},
 disclosure:{title:"Responsible Disclosure",intro:"Guidance for reporting a suspected security issue responsibly.",sections:[{title:"Reporting",body:"Security reporting address and acknowledgement timeline: OWNER_REVIEW_REQUIRED. Do not access, alter, retain, or disclose other people’s data."},{title:"Scope",body:"Good-faith testing must avoid denial of service, social engineering, automated account abuse, and destructive activity."}]},
 dpa:{title:"Data Processing Information",intro:"A high-level summary of data handling; this is not a signed data processing agreement.",sections:[{title:"Processing",body:"Order, delivery, account, support, and security data are processed to provide requested services and protect the platform."},{title:"Legal terms",body:commonReview}]},
 acceptable:{title:"Acceptable Use Policy",intro:"Rules for safe and lawful use of the storefront.",sections:[{title:"Prohibited activity",body:"Do not abuse accounts, automate fraudulent orders, probe systems without authorization, upload malicious content, or interfere with service availability."},{title:"Enforcement",body:commonReview}]},
 community:{title:"Community Guidelines",intro:"Standards for respectful interactions with QurZaib Fabrics support and services.",sections:[{title:"Respect and safety",body:"Do not submit threats, harassment, unlawful content, impersonation, spam, or another person’s private information."},{title:"Moderation",body:commonReview}]},
};
