"use client";
import Image from "next/image";
import Link from "next/link";
import { ShoppingBag } from "lucide-react";
import { useState } from "react";
import type { Product } from "@/src/types/supabase";
import { productTypeLabels } from "@/src/types/product";
import { activeVariants, effectiveProductPrice, hasValidSale, productHref, productInventory } from "@/src/lib/product-commerce";
const money=(value:number)=>`PKR ${Number(value).toLocaleString("en-PK")}`;
export function ProductCard({product,isNew=false}:{product:Product;isNew?:boolean}) {
  const [failed,setFailed]=useState(false); const type=product.product_type??"unstitched"; const detail=product.details;
  const primary=product.images?.[0]; const secondary=product.images?.[1];
  const variants=activeVariants(product); const sale=hasValidSale(product); const price=effectiveProductPrice(product); const inventory=productInventory(product); const href=productHref(product);
  const descriptor=[productTypeLabels[type],detail?.pieces?`${detail.pieces} Piece`:null,detail?.fabric].filter(Boolean).join(" • ");
  const sizes=new Set(variants.filter(v=>Number(v.stock_quantity)>0).map(v=>v.size).filter(Boolean)).size;
  const colors=new Set(variants.filter(v=>Number(v.stock_quantity)>0).map(v=>v.color_id).filter(Boolean)).size;
  const lowStock=inventory>0&&inventory<=5;
  return <article className="group flex min-w-0 flex-col bg-white text-brand-charcoal"><Link href={href} className="relative block aspect-[3/4] overflow-hidden bg-brand-cream-dark">{primary&&!failed?<><Image src={primary} alt={product.title} fill className={`object-cover transition duration-700 ${secondary?"group-hover:opacity-0":"group-hover:scale-[1.03]"}`} sizes="(max-width:640px) 50vw,(max-width:1024px) 33vw,25vw" onError={()=>setFailed(true)}/>{secondary&&<Image src={secondary} alt="" fill className="object-cover opacity-0 transition duration-700 group-hover:opacity-100" sizes="(max-width:640px) 50vw,(max-width:1024px) 33vw,25vw"/>}</>:<span className="absolute inset-0 grid place-items-center"><ShoppingBag className="text-brand-green/35"/></span>}<span className="absolute left-2 top-2 flex flex-col items-start gap-1">{(isNew||product.is_new)&&<span className="bg-white px-2.5 py-1 text-[9px] font-bold tracking-[.16em]">NEW</span>}{sale&&<span className="bg-brand-green-dark px-2.5 py-1 text-[9px] font-bold text-white">SALE</span>}{lowStock&&<span className="bg-white px-2.5 py-1 text-[9px] font-bold text-error">LOW STOCK</span>}</span>{inventory<=0&&<span className="absolute inset-x-0 bottom-0 bg-brand-charcoal/85 py-2 text-center text-[10px] font-semibold text-white">SOLD OUT</span>}</Link><div className="flex flex-1 flex-col px-3 pb-3 pt-2.5 sm:px-4"><p className="text-[9px] uppercase tracking-[.18em] text-accent">{product.category_record?.name??product.category}</p><Link href={href} className="mt-1.5 line-clamp-2 min-h-10 text-xs leading-5 hover:text-accent sm:text-sm">{product.title}</Link>{descriptor&&<p className="mt-1 line-clamp-1 text-xs text-muted">{descriptor}</p>}{type==="ready_to_wear"&&sizes>0&&<p className="mt-1 text-xs text-muted">{sizes} {sizes===1?"size":"sizes"} available</p>}{type!=="ready_to_wear"&&colors>0&&<p className="mt-1 text-xs text-muted">{colors} {colors===1?"color":"colors"} available</p>}<div className="mt-2.5 flex flex-wrap gap-2 text-xs"><strong>{money(price)}{type==="loose_fabric"&&detail?.selling_unit?` / ${detail.selling_unit}`:""}</strong>{sale&&<span className="text-muted line-through">{money(Number(product.compare_at_price??product.price))}</span>}</div><Link href={href} className="mt-4 min-h-11 border border-brand-green-dark bg-brand-green-dark px-3 py-3 text-center text-[10px] font-semibold tracking-[.14em] text-white">{variants.length?"Choose Options":"View Product"}</Link></div></article>;
}
